---
abstract: 'scraping edgar for fun and profit'
author:
  - 'Andrew Shapiro <trski@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Finance-SEC-EdgarData
no_index:
  directory:
    - t
    - inc
requires:
  XML::Bare: 0.53
  Mojolicious: 8.26
  JSON::XS: 4.02
  Test::More: 0
version: 0.01
